/*
 * This raw data was gathered from WikiFur's page on conventions at
 * < http://en.wikifur.com/wiki/Timeline_of_charity_donations > which
 * is generated by MediaWiki.  Editing that page will show the raw data.
 * That data was munged into the format below using regular expressions,
 * then munged further into a format that can be simply dumped into D3's
 * stack layout below.  This is done to make replacing the raw data
 * relatively easy.
 *
 * NB: there were two additions: FC's data for 2011 and 2012 was available
 *     both from WikiFur as well as SmackJackal, the convention's current
 *     chair (2011 data corrected via twitter).
 */
var rawData = [
    { year: 1997, conventions: [
        { key: 'AC', name: 'Albany Anthrocon 1997', amount: 2200 } 
    ]},
    { year: 1998, conventions: [
        { key: 'AC', name: 'Albany Anthrocon 1998', amount: 3092 }
    ]},
    { year: 1999, conventions: [
        { key: 'AC', name: 'Anthrocon 1999', amount: 3485 },
        { key: 'FC', name: 'Further Confusion 1999', amount: 3500 } // includes FurDance '99
    ]},
    { year: 2000, conventions: [
        { key: 'AC', name: 'Anthrocon 2000', amount: 6500 },
        { key: 'FC', name: 'Further Confusion 2000', amount: 6000 },
        { key: 'MFF', name: 'Midwest FurFest 2000', amount: 3522 }
    ]},
    { year: 2001, conventions: [
        { key: 'AC', name: 'Anthrocon 2001', amount: 7273 },
        { key: 'FC', name: 'Further Confusion 2001', amount: 7240 },
        { key: 'MFF', name: 'Midwest FurFest 2001', amount: 6800 },
        { key: 'MFM', name: 'Mephit Furmeet 2001', amount: 6000 },
        { key: 'CFN', name: 'Conifur Northwest 2001', amount: 1550 }
    ]},
    { year: 2002, conventions: [
        { key: 'AC', name: 'Anthrocon 2002', amount: 13280 },
        { key: 'FC', name: 'Further Confusion 2002', amount: 5200 },
        { key: 'MFF', name: 'Midwest FurFest 2002', amount: 6088 },
        { key: 'MFM', name: 'Mephit Furmeet 2002', amount: 7000 }
    ]},
    { year: 2003, conventions: [
        { key: 'AC', name: 'Anthrocon 2003', amount: 8348 },
        { key: 'FC', name: 'Further Confusion 2003', amount: 6000 },
        { key: 'MFF', name: 'Midwest FurFest 2003', amount: 6500 },
        { key: 'MFM', name: 'Mephit Furmeet 2003', amount: 7000 },
        { key: 'CFN', name: 'Conifur Northwest 2003', amount: 3011 }
    ]},
    { year: 2004, conventions: [
        { key: 'AC', name: 'Anthrocon 2004', amount: 7200 },
        { key: 'MOR', name: 'Morphicon 2004', amount: 350 },
        { key: 'FC', name: 'Further Confusion 2004', amount: 10000 },
        { key: 'FF', name: 'FurFright 2004', amount: 500 },
        { key: 'MFF', name: 'Midwest FurFest 2004', amount: 7000 },
        { key: 'RCFM', name: 'Rocket City FurMeet 2004', amount: 1000 },
        { key: 'MFM', name: 'Mephit FurMeet 8', amount: 15000 }, 
        { key: 'CFN', name: 'Conifur Northwest 2004', amount: 2248 },
        { key: 'OKL', name: 'Oklacon 2004', amount: 1600 }
    ]},
    { year: 2005, conventions: [
        { key: 'AC', name: 'Anthrocon 2005', amount: 6470 },
        { key: 'MOR', name: 'Morphicon 2005', amount: 844 },
        { key: 'FC', name: 'Further Confusion 2005', amount: 10000 },
        { key: 'FF', name: 'FurFright 2005', amount: 1059 },
        { key: 'MFF', name: 'Midwest FurFest 2005', amount: 6800 },
        { key: 'RCFM', name: 'Rocket City FurMeet 2005', amount: 1200 },
        { key: 'MFM', name: 'Mephit FurMeet 9', amount: 16600 },
        { key: 'FWA', name: 'Furry Weekend Atlanta 2005', amount: 2900 },
        { key: 'OKL', name: 'Oklacon 2005', amount: 4000 }
    ]},
    { year: 2006, conventions: [
        { key: 'AC', name: 'Anthrocon 2006', amount: 8407 },
        { key: 'MOR', name: 'Morphicon 2006', amount: 566 },
        { key: 'FC', name: 'Further Confusion 2006', amount: 15000 },
        { key: 'FF', name: 'FurFright 2006', amount: 1631 },
        { key: 'MFF', name: 'Midwest FurFest 2006', amount: 13049 },
        { key: 'RCFM', name: 'Rocket City FurMeet 2006', amount: 1364 },
        { key: 'MFM', name: 'Mephit FurMeet X', amount: 12121 }, 
        { key: 'FWA', name: 'Furry Weekend Atlanta 2006', amount: 3900 },
        { key: 'OKL', name: 'Oklacon 2006', amount: 2300 },
        { key: 'WPFW', name: 'Western Pennsylvania Furry Weekend', amount: 2000 }
    ]},
    { year: 2007, conventions: [
        { key: 'AC', name: 'Anthrocon 2007', amount: 7608 },
        { key: 'MOR', name: 'Morphicon 2007', amount: 1000 },
        { key: 'WPFW', name: 'Western Pennsylvania Furry Weekend', amount: 657 },
        { key: 'FC', name: 'Further Confusion 2007', amount: 16000 },
        { key: 'FF', name: 'FurFright 2007', amount: 3000 },
        { key: 'EF', name: 'Eurofurence 13', amount: 2628 },
        { key: 'MFM', name: 'Mephit FurMeet 11', amount: 9000 },
        { key: 'RBW', name: 'RBW 2007', amount: 2662 },
        { key: 'FAU', name: 'FA United 2007', amount: 1600 },
        { key: 'OKL', name: 'Oklacon 2007', amount: 5277 },
        { key: 'RF', name: 'Rainfurrest 2007', amount: 900 },
        { key: 'MFF', name: 'Midwest FurFest 2007', amount: 15193 },
        { key: 'RCFM', name: 'Rocket City FurMeet 2007', amount: 1768 },
        { key: 'CES', name: 'CeSFuR 2007', amount: 1109 }
    ]},
    { year: 2008, conventions: [
        { key: 'AC', name: 'Anthrocon 2008', amount: 13154 },
        { key: 'MOR', name: 'Morphicon 2008', amount: 2000 },
        { key: 'WPFW', name: 'Western Pennsylvania Furry Weekend', amount: 1200 },
        { key: 'MFM', name: 'Mephit FurMeet 12', amount: 10000 },
        { key: 'MPLX', name: 'Megaplex 7', amount: 1185 },
        { key: 'FC', name: 'Further Confusion 2008', amount: 22000 },
        { key: 'FF', name: 'FurFright 2008', amount: 4000 },
        { key: 'MID', name: 'MiDFur', amount: 3540 },
        { key: 'EF', name: 'Eurofurence 14', amount: 5200 },
        { key: 'RBW', name: 'RBW 2008', amount: 1850 },
        { key: 'FAU', name: 'FA United 2008', amount: 1820 },
        { key: 'OKL', name: 'Oklacon 2008', amount: 4700 },
        { key: 'RF', name: 'Rainfurrest 2008', amount: 1000 },
        { key: 'MFF', name: 'Midwest FurFest 2008', amount: 15000 },
        { key: 'RCFM', name: 'Rocket City FurMeet 2008', amount: 3536 },
        { key: 'CES', name: 'CeSFuR', amount: 665 },
        { key: 'FWA', name: 'Furry Weekend Atlanta 2008', amount: 5001 },
        { key: 'FUTR', name: 'Futrzakon 2008', amount: 430 },
        { key: 'CFZ', name: 'ConFuzzled 2008', amount: 3160 }
    ]},
    { year: 2009, conventions: [
        { key: 'AC', name: 'Anthrocon 2009', amount: 8992 },
        { key: 'MOR', name: 'Morphicon 2009', amount: 1400 },
        { key: 'WPFW', name: 'Western Pennsylvania Furry Weekend', amount: 1200 },
        { key: 'FC', name: 'Further Confusion 2009', amount: 15000 },
        { key: 'FUTR', name: 'Futrzakon 2009', amount: 645 },
        { key: 'MFF', name: 'Midwest FurFest 2009', amount: 12791 },
        { key: 'FCN', name: 'Furry Connection North 2009', amount: 280 },
        { key: 'RF', name: 'Rainfurrest 2009', amount: 536 },
        { key: 'MFM', name: 'Mephit FurMeet 13', amount: 5472 },
        { key: 'OKL', name: 'Oklacon 2009', amount: 3200 },
        { key: 'EF', name: 'Eurofurence 15', amount: 4225 },
        { key: 'RCFM', name: 'Rocket City FurMeet 2009', amount: 2162 },
        { key: 'FF', name: 'FurFright 2009', amount: 7770 },
        { key: 'MID', name: 'MiDFur', amount: 5260 },
        { key: 'FAU', name: 'FA United 3', amount: 2458 },
        { key: 'RBW', name: 'RBW 2009', amount: 3140 },
        { key: 'FWA', name: 'Furry Weekend Atlanta 2009', amount: 5054 },
        { key: 'MPLX', name: 'Megaplex 8', amount: 1500 },
        { key: 'FFI', name: 'Furry Fiesta 2009', amount: 2700 },
        { key: 'CFZ', name: 'ConFuzzled 2009', amount: 3183 },
        { key: 'CES', name: 'CeSFuR', amount: 650 }
    ]},
    { year: 2010, conventions: [
        { key: 'AC', name: 'Anthrocon 2010', amount: 12849 },
        { key: 'FC', name: 'Further Confusion 2010', amount: 18114 },
        { key: 'MFF', name: 'Midwest FurFest 2010', amount: 11300 },
        { key: 'MFM', name: 'Mephit FurMeet 14', amount: 6289 },
        { key: 'MOR', name: 'Morphicon 2010', amount: 2116 },
        { key: 'WTF', name: 'What The Fur 2010', amount: 694 },
        { key: 'OKL', name: 'Oklacon 2010', amount: 5365 },
        { key: 'RCFM', name: 'Rocket City FurMeet 2010', amount: 2488 },
        { key: 'EF', name: 'Eurofurence 16', amount: 7500 },
        { key: 'FAU', name: 'FA United 4', amount: 2458 },
        { key: 'RBW', name: 'RBW 2010', amount: 10233 },
        { key: 'IFC', name: 'IndyFurCon', amount: 1150 },
        { key: 'FF', name: 'FurFright 2010', amount: 12456 },
        { key: 'FWA', name: 'Furry Weekend Atlanta 2010', amount: 4600 },
        { key: 'MPLX', name: 'Megaplex 9', amount: 2918 },
        { key: 'MID', name: 'MiDFur', amount: 8173 },
        { key: 'CES', name: 'CeSFuR', amount: 750 },
        { key: 'FFI', name: 'Furry Fiesta 2010', amount: 3600 },
        { key: 'CFZ', name: 'ConFuzzled 2010', amount: 9920 },
        { key: 'FE', name: 'Furnal Equinox 2010', amount: 194 },
        { key: 'WPFW', name: 'Western Pennsylvania Furry Weekend', amount: 1200 },
        { key: 'CON', name: 'Condition: Zero Hour', amount: 2132 }
    ]},
    { year: 2011, conventions: [
        { key: 'AC', name: 'Anthrocon 2011', amount: 11522 },
        { key: 'FC', name: 'Further Confusion 2011', amount: 10000 },
        { key: 'RCFM', name: 'Rocket City FurMeet 2011', amount: 2257 },
        { key: 'FFI', name: 'Furry Fiesta 2011', amount: 4100 },
        { key: 'FCN', name: 'Furry Connection North 2011', amount: 5000 },
        { key: 'FAU', name: 'FA United 4', amount: 3544 },
        { key: 'FE', name: 'Furnal Equinox 2011', amount: 4108 },
        { key: 'CFZ', name: 'ConFuzzled 2011', amount: 16362 },
        { key: 'WTF', name: 'What The Fur 2011', amount: 2271 },
        { key: 'CON', name: 'Condition: Red', amount: 10685 },
        { key: 'MPLX', name: 'Megaplex', amount: 1268 },
        { key: 'EF', name: 'Eurofurence 17', amount: 12549 },
        { key: 'OKL', name: 'Oklacon 2011', amount: 8194 },
        { key: 'IFC', name: 'IndyFurCon', amount: 1212 },
        { key: 'MFF', name: 'Midwest FurFest 2011', amount: 19575 },
        { key: 'FF', name: 'FurFright 2011', amount: 12850 },
        { key: 'CES', name: 'CeSFuR', amount: 579 },
        { key: 'MFM', name: 'Mephit Fur Meet 15', amount: 14059 },
        { key: 'RMFC', name: 'Rocky Mountain Fur Con 2011', amount: 1200 }
    ]},
    { year: 2012, conventions: [
        { key: 'AC', name: 'Anthrocon 2012', amount: 20656 },
        { key: 'FC', name: 'Further Confusion 201', amount: 7000 },
        { key: 'RCFM', name: 'Rocket City FurMeet 2012', amount: 2000 },
        { key: 'FCN', name: 'Furry Connection North 2012', amount: 5000 },
        { key: 'FAU', name: 'FA United 5', amount: 8076 },
        { key: 'WTF', name: 'What The Fur 2012', amount: 4150 },
        { key: 'CFZ', name: 'ConFuzzled 2012', amount: 12162 },
        { key: 'FWA', name: 'Furry Weekend Atlanta 2012', amount: 18000 },
        { key: 'FFI', name: 'Furry Fiesta 2012', amount: 9067 },
        { key: 'CES', name: 'CeSFuR', amount: 526 },
        { key: 'FE', name: 'Furnal Equinox 2012', amount: 8068 },
        { key: 'MID', name: 'MiDFur', amount: 8239 },
        { key: 'MPLX', name: 'Megaplex XI', amount: 4302 },
        { key: 'IFC', name: 'IndyFurCon', amount: 2500 },
        { key: 'CON', name: 'Condition: Blue', amount: 10120 },
        { key: 'SCO', name: 'ScotiaCon', amount: 3264 },
        { key: 'EF', name: 'Eurofurence 18', amount: 16673 },
        { key: 'RMFC', name: 'Rocky Mountain Fur Con 2012', amount: 2500 },
        { key: 'OKL', name: 'Oklacon 2012', amount: 9250 },
        { key: 'FF', name: 'FurFright 2012', amount: 15445 },
        { key: 'MFF', name: 'Midwest FurFest 2012', amount: 40500 }
    ]}
];

var data = {};

rawData.forEach(function(year) {
    year.conventions.forEach(function(convention) {
        if (!data[convention.key]) {
            data[convention.key] = [];
        }

        data[convention.key].push({ 
            year: year.year, 
            amount: convention.amount, 
            label: convention.name 
        });
    });
});

Object.keys(data).forEach(function (key) {
    var yearsInCon = data[key].map(function(d) { return d.year; });
    for (var year = 1997; year <= 2012; year++) {
        if (yearsInCon.indexOf(year) === -1) {
            data[key].push({
                year: year,
                amount: 0,
                label: '[no con this year]'
            });
        }
    }
    data[key] = data[key].sort(function(a, b) { return a.year - b.year; })
});
