var statesData = {
	"Alabama": 25,
	"Alaska": 7,
	"Arizona": 45,
	"Arkansas": 5,
	"California": 114,
	"Colorado": 29,
	"Connecticut": 18,
	"Delaware": 8,
	"Florida": 73,
	"Georgia": 29,
	"Hawai'i": 8,
	"Idaho": 12,
	"Illinois": 31,
	"Indiana": 24,
	"Iowa": 21,
	"Kansas": 17,
	"Kentucky": 18,
	"Louisiana": 18,
	"Maine": 7,
	"Maryland": 26,
	"Massachusetts": 29,
	"Michigan": 29,
	"Minnesota": 26,
	"Mississippi": 4,
	"Missouri": 30,
	"Montana": 17,
	"Nebraska": 8,
	"Nevada": 9,
	"New Hampshire": 4,
	"New Jersey": 37,
	"New Mexico": 11,
	"New York": 65,
	"North Carolina": 33,
	"North Dakota": 5,
	"Ohio": 41,
	"Oklahoma": 15,
	"Oregon": 23,
	"Pennsylvania": 48,
	"Rhode Island": 4,
	"South Carolina": 17,
	"South Dakota": 3,
	"Tennessee": 30,
	"Texas": 68,
	"Utah": 21,
	"Vermont": 3,
	"Virginia": 38,
	"Washington": 32,
	"Wisconsin": 26,
	"West Virginia": 4,
	"Wyoming": 5,
};
